import type { FormAnswers, QuestionDef, StepDef } from "./types";

export const STEPS: StepDef[] = [
  {
    id: 1,
    name: "About you",
    description: "Who you are and how close you are to the work.",
  },
  {
    id: 2,
    name: "What is this?",
    description: "Name it and describe the work in plain language.",
  },
  {
    id: 3,
    name: "How much work?",
    description: "Frequency, duration, and people involved.",
  },
  {
    id: 4,
    name: "How it works today",
    description: "Trigger, steps, tools, and output.",
  },
  {
    id: 5,
    name: "How repeatable?",
    description: "Rules, data shape, and handoffs.",
  },
  {
    id: 6,
    name: "Pain & risk",
    description: "What hurts, what breaks, and why it matters.",
  },
  {
    id: 7,
    name: "What should change?",
    description: "Scope, success, and readiness.",
  },
];

const hasDocuments = (answers: FormAnswers) => {
  const v = answers.Q28;
  return v === "Sometimes" || v === "Most of the time";
};

const hasSensitiveData = (answers: FormAnswers) => {
  const v = answers.Q38;
  if (!Array.isArray(v)) return false;
  return v.some(
    (item) =>
      item !== "None of these" &&
      (item.includes("personal") ||
        item.includes("Money") ||
        item.includes("Contracts")),
  );
};

export const QUESTIONS: QuestionDef[] = [
  {
    id: "Q1",
    step: 1,
    title: "Your name",
    helper: "So we know who to follow up with.",
    type: "text",
    required: true,
    placeholder: "Jane Smith",
  },
  {
    id: "Q2",
    step: 1,
    title: "Work email",
    helper: "Used only for follow-up questions.",
    type: "email",
    required: true,
    placeholder: "jane@company.com",
  },
  {
    id: "Q3",
    step: 1,
    title: "Do you personally do this work?",
    helper: "Honest answers help us assess confidence in the submission.",
    type: "single",
    required: true,
    options: [
      "Yes, I do it regularly",
      "I cover it sometimes / used to do it",
      "I manage people who do it",
      "I am describing something I have heard about",
    ],
  },
  {
    id: "Q4",
    step: 1,
    title: "Who else should we talk to?",
    helper: "Optional — someone who does the work day to day.",
    type: "text",
    required: false,
    placeholder: "Name or email",
  },
  {
    id: "Q5",
    step: 2,
    title: "Which area of the business is this?",
    type: "single",
    required: true,
    options: [
      "Sales",
      "Customer service / support",
      "Finance / accounts",
      "Operations / delivery",
      "HR / people",
      "Marketing",
      "Procurement / supply chain",
      "Legal / compliance",
      "IT / admin",
      "Other",
    ],
  },
  {
    id: "Q6",
    step: 2,
    title: "Give this a short name",
    helper: 'Like a task title — e.g. "Monthly supplier invoice checks".',
    type: "text",
    required: true,
    placeholder: "Short descriptive title",
  },
  {
    id: "Q7",
    step: 2,
    title: "In one sentence, what is this work?",
    helper: "Imagine telling a new starter.",
    type: "textarea",
    required: true,
    placeholder: "We receive supplier invoices by email and...",
  },
  {
    id: "Q8",
    step: 2,
    title: "What is most of the manual work?",
    helper: "Pick the one that best describes where your time goes.",
    type: "single",
    required: true,
    options: [
      "Copying or moving data between places",
      "Checking or validating numbers / figures",
      "Creating or formatting reports",
      "Chasing people or waiting for responses",
      "Finding and gathering information",
      "A mix of several of these",
    ],
  },
  {
    id: "Q9",
    step: 2,
    title: "If you check figures, what are you comparing?",
    helper: "Skip mentally if checking is not a big part of this task — pick the first option.",
    type: "single",
    required: true,
    options: [
      "Not much checking — mostly moving or entering data",
      "Against a fixed rule or checklist (e.g. must balance, must match a PO)",
      "Two systems or spreadsheets that should agree",
      "Against a prior period, budget, or forecast",
      "Each case is different — needs judgment",
    ],
  },
  {
    id: "Q10",
    step: 2,
    title: "How is this done today?",
    type: "single",
    required: true,
    options: [
      "Fully done by people",
      "Helped by Excel macros / templates",
      "Some software already, still lots of manual work",
      "We tried to improve this before and it stalled",
    ],
  },
  {
    id: "Q11",
    step: 3,
    title: "How often does this happen?",
    helper: "How often a person has to pick it up.",
    type: "single",
    required: true,
    options: [
      "Many times a day",
      "About once a day",
      "A few times a week",
      "Weekly",
      "Monthly",
      "Quarterly",
      "A few times a year / when something comes up",
    ],
  },
  {
    id: "Q12",
    step: 3,
    title: "Roughly how many times in that period?",
    helper: "If daily: per day. If monthly: per month. A range is fine (e.g. 10-15).",
    type: "text",
    required: true,
    placeholder: "e.g. 5 or 10-15",
  },
  {
    id: "Q13",
    step: 3,
    title: "How long does one go take, start to finish?",
    helper: "Include looking things up and checking. Exclude overnight waiting.",
    type: "single",
    required: true,
    options: [
      "Under 15 min",
      "15–30 min",
      "30–60 min",
      "1–2 hours",
      "2–4 hours",
      "Half a day",
      "A full day or more",
    ],
  },
  {
    id: "Q14",
    step: 3,
    title: "How much is waiting vs actually doing the work?",
    type: "single",
    required: true,
    options: [
      "Almost all doing",
      "Mix of doing and waiting",
      "Mostly waiting",
    ],
  },
  {
    id: "Q15",
    step: 3,
    title: "How many people spend time on this?",
    type: "single",
    required: true,
    options: ["1", "2–3", "4–7", "8 or more"],
  },
  {
    id: "Q16",
    step: 3,
    title: "Does this get much busier at certain times?",
    type: "single",
    required: true,
    options: [
      "Steady year-round",
      "Busy at week/month/quarter end",
      "Seasonal peaks",
      "Unpredictable spikes",
    ],
  },
  {
    id: "Q17",
    step: 3,
    title: "If this work piles up, what happens?",
    helper: "Select all that apply.",
    type: "multi",
    required: true,
    options: [
      "Deadlines slip",
      "People work overtime",
      "More mistakes",
      "Management or leadership notices",
      "It just waits — no big deal",
    ],
  },
  {
    id: "Q18",
    step: 3,
    title: "Optional: team time per typical week (your guess)",
    helper: "We'll also calculate this — this is a sanity check.",
    type: "single",
    required: false,
    options: [
      "Under 2 hours",
      "2–8 hours",
      "About 1–2 days",
      "3–5 days",
      "More than one full-time person",
      "Not sure",
    ],
  },
  {
    id: "Q19",
    step: 4,
    title: "What usually kicks this off?",
    type: "single",
    required: true,
    options: [
      "An email arrives",
      "A form or request comes in",
      "A date / calendar (e.g. every Friday)",
      "Something changes in a system",
      "Someone asks in chat or in person",
      "I notice it myself",
      "Other",
    ],
  },
  {
    id: "Q20",
    step: 4,
    title: "Walk through the main steps",
    helper: "One short line per step. Aim for 4–6 steps.",
    type: "steps",
    required: true,
  },
  {
    id: "Q21",
    step: 4,
    title: "Which tools do you touch?",
    helper: "Select every place you look at or type into.",
    type: "multi",
    required: true,
    options: [
      "Excel / Google Sheets",
      "Email",
      "Word / Docs / PDFs",
      "Shared folder / SharePoint / Drive",
      "Accounting / finance system",
      "CRM",
      "Company intranet / portal",
      "Teams / Slack",
      "Paper / printouts",
      "A supplier, bank, or government website",
      "Other",
    ],
  },
  {
    id: "Q22",
    step: 4,
    title: "What is the finished result?",
    type: "single",
    required: true,
    options: [
      "A spreadsheet or report",
      "A record updated in a system",
      "An email or message sent",
      "An approval given",
      "A file saved in a folder",
      "Something printed or posted",
      "Several of these",
    ],
  },
  {
    id: "Q23",
    step: 4,
    title: "What happens to the result when you are done?",
    helper: "Optional — e.g. saved in a system, emailed to someone, filed away.",
    type: "text",
    required: false,
    placeholder: "Entered in Xero, emailed to manager, filed in shared folder…",
  },
  {
    id: "Q24",
    step: 5,
    title: "Is this mostly the same steps every time?",
    type: "single",
    required: true,
    options: [
      "Yes, same steps almost always",
      "Same overall, but exceptions come up",
      "It depends a lot on the situation",
    ],
  },
  {
    id: "Q25",
    step: 5,
    title: "How often does something unusual come up?",
    type: "single",
    required: true,
    options: [
      "Rarely — most items are straightforward",
      "Sometimes — maybe 1 in 5",
      "Often — maybe 1 in 3",
      "Almost every item is different",
    ],
  },
  {
    id: "Q26",
    step: 5,
    title: "When something unusual happens, what do people do?",
    type: "single",
    required: true,
    options: [
      "Follow a written exception rule",
      "Ask a colleague or manager",
      "Use their experience / judgment",
      "Send it back or skip it",
    ],
  },
  {
    id: "Q27",
    step: 5,
    title: "The information you work with is mostly…",
    type: "single",
    required: true,
    options: [
      "Tables, forms, and fields (numbers, dates, dropdowns)",
      "A mix of tables and emails or notes",
      "Mostly emails, PDFs, scans, or conversations",
    ],
  },
  {
    id: "Q28",
    step: 5,
    title: "Do you work with PDFs, scans, photos, or paper?",
    type: "single",
    required: true,
    options: ["Almost never", "Sometimes", "Most of the time"],
  },
  {
    id: "Q29",
    step: 5,
    title: "Are those documents in a similar layout each time?",
    type: "single",
    required: false,
    showIf: hasDocuments,
    options: [
      "Same template / same layout",
      "Similar but they vary",
      "All different",
    ],
  },
  {
    id: "Q30",
    step: 5,
    title: "Mixed languages or country formats?",
    type: "single",
    required: false,
    showIf: hasDocuments,
    options: ["No, all the same", "Sometimes", "Regularly"],
  },
  {
    id: "Q31",
    step: 5,
    title: "How does information move between tools?",
    helper: "Copy-paste is a valid answer and often a good automation target.",
    type: "single",
    required: true,
    options: [
      "I copy and paste",
      "I download a file and upload it somewhere else",
      "I re-type it",
      "The systems already pass some of it through",
      "Mix of the above",
    ],
  },
  {
    id: "Q32",
    step: 5,
    title: "Has the process changed much in the last 6 months?",
    type: "single",
    required: true,
    options: [
      "Stable",
      "Small tweaks",
      "Changed quite a bit",
      "We are redesigning it now",
    ],
  },
  {
    id: "Q33",
    step: 6,
    title: "What is painful about it today?",
    helper: "Pick up to 3.",
    type: "multi",
    required: true,
    maxSelect: 3,
    options: [
      "Takes too long",
      "Easy to make mistakes",
      "Boring / repetitive",
      "Hunting for the right information",
      "Chasing other people",
      "Re-doing work when something comes back wrong",
      "Only one or two people know how",
      "Stressful when it is busy",
    ],
  },
  {
    id: "Q34",
    step: 6,
    title: "Where does most of the time actually go?",
    type: "single",
    required: true,
    options: [
      "Finding / gathering information",
      "Typing or copying data",
      "Checking and validating",
      "Formatting reports",
      "Fixing mistakes",
      "Waiting / chasing",
    ],
  },
  {
    id: "Q35",
    step: 6,
    title: "How many people know how to do this start to finish?",
    type: "single",
    required: true,
    options: ["Only 1", "2", "3–5", "Many people"],
  },
  {
    id: "Q36",
    step: 6,
    title: "If the usual person is off sick, what happens?",
    type: "single",
    required: true,
    options: [
      "Someone else can cover easily",
      "It waits until they are back",
      "We scramble / quality drops",
    ],
  },
  {
    id: "Q37",
    step: 6,
    title: "What if this is done wrong?",
    type: "single",
    required: true,
    options: [
      "Small inconvenience — we fix it later",
      "Extra rework for the team",
      "Money lost or spent wrongly",
      "Customer complaint",
      "Legal, tax, or compliance problem",
    ],
  },
  {
    id: "Q38",
    step: 6,
    title: "Does this work involve any of these?",
    helper: "Select all that apply.",
    type: "multi",
    required: true,
    options: [
      "People's personal details",
      "Money, invoices, or payments",
      "Contracts or legal documents",
      "Health and safety",
      "None of these",
    ],
  },
  {
    id: "Q39",
    step: 6,
    title: "Do you need a record of who did what?",
    type: "single",
    required: false,
    showIf: hasSensitiveData,
    options: ["Yes, we must keep a trail", "Nice to have", "Not really"],
  },
  {
    id: "Q40",
    step: 6,
    title: "Is there a hard deadline or expected turnaround?",
    type: "single",
    required: true,
    options: [
      "Yes — missing it has consequences",
      "There is an expected turnaround, a bit flexible",
      "No real deadline",
    ],
  },
  {
    id: "Q41",
    step: 6,
    title: "Main reason you would want this improved?",
    type: "single",
    required: true,
    options: [
      "Save time",
      "Fewer mistakes",
      "Reduce cost",
      "Reduce risk (key person or compliance)",
      "Faster for customers",
      "We cannot keep up with the volume",
      "Several of these equally",
    ],
  },
  {
    id: "Q42",
    step: 7,
    title: "Which parts would you like automated?",
    helper: "Select all that apply.",
    type: "multi",
    required: true,
    options: [
      "The whole process, end to end",
      "Moving data between systems or files",
      "Checking / validating",
      "Creating the report or output",
      "Reminders and chasing",
      "Not sure — tell me what is realistic",
    ],
  },
  {
    id: "Q43",
    step: 7,
    title: "What should a person still do?",
    type: "multi",
    required: true,
    options: [
      "Approvals / sign-off",
      "Talking to customers",
      "Handling the unusual cases",
      "Nothing — automate it all if possible",
    ],
  },
  {
    id: "Q44",
    step: 7,
    title: "In three months, how would you know this worked?",
    helper: "Pick up to 2.",
    type: "multi",
    required: true,
    maxSelect: 2,
    options: [
      "Hours saved each week",
      "Fewer errors",
      "Faster turnaround",
      "Less overtime / less stress",
      "We can grow volume without hiring",
      "It no longer depends on one person",
    ],
  },
  {
    id: "Q45",
    step: 7,
    title: "Could you show this live or share examples?",
    type: "single",
    required: true,
    options: [
      "I can walk someone through it",
      "I can share example files or emails",
      "Both",
      "Not easily",
    ],
  },
  {
    id: "Q46",
    step: 7,
    title: "Who would need to agree to change this?",
    type: "multi",
    required: true,
    options: [
      "My manager",
      "IT",
      "Another department",
      "Finance / compliance",
      "I do not know",
    ],
  },
  {
    id: "Q47",
    step: 7,
    title: "How soon would this help?",
    type: "single",
    required: true,
    options: [
      "We are struggling now",
      "This quarter would be valuable",
      "This year is fine",
      "Just capturing the idea for later",
    ],
  },
  {
    id: "Q48",
    step: 7,
    title: "Anything else we should know?",
    type: "textarea",
    required: false,
    placeholder: "Workarounds, objections, previous failed tools...",
  },
];

export function getQuestionsForStep(
  step: number,
  answers: FormAnswers,
): QuestionDef[] {
  return QUESTIONS.filter((q) => {
    if (q.step !== step) return false;
    if (q.showIf && !q.showIf(answers)) return false;
    return true;
  });
}

export function getQuestionLabel(id: string): string {
  return QUESTIONS.find((q) => q.id === id)?.title ?? id;
}

export function formatAnswerValue(
  id: string,
  value: string | string[] | undefined,
): string {
  if (value === undefined || value === "") return "—";
  if (Array.isArray(value)) {
    if (value.length === 0) return "—";
    return value.filter(Boolean).join(", ");
  }
  return value;
}
